services:
  - type: web
    name: semantic-similarity-api
    env: python
    pythonVersion: "3.12"  
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000 --timeout-keep-alive 30
    envVars:
      - key: HF_TOKEN
        sync: false  
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONFAULTHANDLER
        value: "1"  
    plan: free  
    autoDeploy: true
    healthCheckPath: /health
